baseURL: http://estatsej.com.br/
languageCode: pt-br
title: Estats Consultoria
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0
params:
  google_analytics_id: 'G-X7ZPHTZQWS'
  homepage_meta_tags:
    meta_description: Transformando seus dados em soluções.
    meta_og_description: Transformando seus dados em soluções.
    meta_og_image: images/preview.png
    meta_og_title: Estats Consultoria
    meta_og_type: website
    meta_og_url: http://estatsej.com.br/
    meta_twitter_card: summary
  logo:
    alt: Estats
    desktop: images/estatslogo.png
    desktop_height: 29px
    desktop_width: 217px
    mobile: images/logomobile.png
    mobile_height: 36px
    mobile_width: 36px
menu:
  main:
    - name: Serviços
      url: /services/
      weight: 1
    - name: Sobre nós
      url: /about/
      weight: 3
    - name: Contatos
      url: /contact/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
